- name: Configure Git and Nginx
  hosts: localhost
  tasks:
    - name: Install Git
      apt:
        name: git
        state: present

    - name: Install Nginx
      apt:
        name: nginx
        state: present

