---
- name: Configure Git and Nginx using roles
  hosts: ec2
  become: yes
  connection: aws_ssm   # aws_ssm を使用（ecgalaxy.aws_ssm でも使用可）
  gather_facts: no      # 必要に応じて変更
  vars:
    ansible_aws_ssm_region: "ap-northeast-1"  # 東京リージョン
    ansible_python_interpreter: "/usr/bin/python"  # Pythonインタプリタパス
    # ecgalaxy.aws_ssm で必要な追加パラメーター（必要に応じて）
    # ansible_aws_ssm_timeout: 60
    # ansible_aws_ssm_bucket_name: "ansible-ssm-bucket-AnsibleStackS3"

  roles:
    - role: myrole/git
    - role: myrole/nginx

