- name: Manage CloudFormation stack
  hosts: localhost
  tasks:
    - name: Create or update CloudFormation stack
      amazon.aws.cloudformation:
        stack_name: "MyStack"
        state: present
        template_body: "{{ lookup('file', 'VPCtest2406.yml') }}" # VPCのCFnテンプレート
        region: "ap-northeast-1"  # 東京リージョン
