---
- name: Configure Git and Nginx using roles
  hosts: all
  become: yes
  gather_facts: no
  vars:
    ansible_python_interpreter: "/usr/bin/python"
  roles:
    - role: myrole/git
    - role: myrole/nginx


