version: 2.1

executors:
  python:
    docker:
      - image: cimg/python:3.13.3  # PythonのDockerイメージを使用

commands:
  install-dependencies:
    description: "Install required dependencies"
    steps:
      - run:
          name: Install dependencies  # 依存関係をインストール
          command: |  
            sudo apt update 
            # APTでインストール可能なパッケージをインストール
            sudo apt install -y python3 python3-pip awscli ansible python3-boto3 python3-botocore  
            # 必要に応じてpipで追加の依存関係をインストール
            # pip3 install --upgrade pip  
            ansible-galaxy collection install amazon.aws --force  # 必要なコレクションをインストール
  check-python-version:
  # Pythonのバージョンを確認するためのコマンド
    description: "check python version"
    steps:
      - run:
          name: check python version  # Pythonのバージョンを確認
          command: |
            python --version  

jobs:
  setup-environment:
    executor: python
    steps:
      - checkout  # リポジトリをチェックアウト
      - check-python-version # Pythonのバージョンを確認
      - install-dependencies  # ここでcommandsを呼び出し
      - run:
          name: Verify Ansible and AnsiblePlaybook Installation # AnsibleとAnsiblePlaybookのインストール確認
          command: |
            which ansible
            ansible --version
            which ansible-playbook
            ansible-playbook --version
      - run:
          name: Check Installed Files # インストールされたファイルを確認
          command: | 
            ls -la ~/.local 
            ls -la ~/.local/bin 
      - run:
          name: Create CloudFormation Stack for VPC # VPCスタックを作成
          command: |
            aws cloudformation deploy \
              --template-file VPCtest2406.yml \
              --stack-name AnsibleStackVPC \
              --region ap-northeast-1 \
              --capabilities CAPABILITY_NAMED_IAM 
      - run:
          name: Create CloudFormation Stack for EC2-ALB-SG  # EC2-ALB-SGスタックを作成
          command: |
            aws cloudformation deploy \
              --template-file EC2,ALB,SG2406.yml \
              --stack-name AnsibleStackEC2-ALB-SG \
              --region ap-northeast-1 \
              --capabilities CAPABILITY_NAMED_IAM
      # - run:
      #     name: Create CloudFormation Stack for RDS # RDSスタックを作成
      #     command: |
      #       aws cloudformation deploy \
      #         --template-file RDStest2406.yml \
      #         --stack-name AnsibleStackRDS \
      #         --region ap-northeast-1 \
      #         --capabilities CAPABILITY_NAMED_IAM
      - run:
          name: Get EC2 Instance ID and Update Inventory  # EC2のインスタンスIDを取得してインベントリを更新
          command: |
            INSTANCE_NAME="AnsibleStackEC2-ALB-SG-ec2-instance" 
            INVENTORY_FILE="myrole/tests/inventory"
            INSTANCE_ID=$(aws ec2 describe-instances \
              --region ap-northeast-1 \
              --filters "Name=tag:Name,Values=${INSTANCE_NAME}" \
              --query "Reservations[*].Instances[*].InstanceId" \
              --output text)
            if [ -z "$INSTANCE_ID" ]; then  
              echo "Error: EC2 Instance ID could not be retrieved." 
              exit 1
            fi
            echo "[ec2]" > $INVENTORY_FILE 
            echo "${INSTANCE_ID} ansible_connection=amazon.aws.ssm" >> $INVENTORY_FILE 
            cat $INVENTORY_FILE  
      - run:
          name: Test Ansible Connection via SSM # Ansibleの接続テスト（SSM経由）
          command: |
            ansible ec2 -i myrole/tests/inventory -m ping > ansible_ping_result.log 2>&1 || {
              echo "Error: Ansible command failed. Check ansible_ping_result.log for details."
              cat ansible_ping_result.log
              exit 1
            }
            if ! grep -q "SUCCESS" ansible_ping_result.log; then
              echo "Error: Ansible connection test failed. Check ansible_ping_result.log for details."
              cat ansible_ping_result.log
              exit 1
            fi

  ansible-playbook: # Ansibleプレイブック実行ジョブ
    executor: python
    steps:
      - checkout
      - install-dependencies  # 再度commandsでインストール
      - run:
          name: Verify Ansible Installation # Ansibleのインストール確認
          command: |
            which ansible
            ansible --version
            which ansible-playbook
            ansible-playbook --version
      - run:
          name: Set Ansible Roles Path  # Ansibleのロールパスを設定
          command: |
            export ANSIBLE_ROLES_PATH=./myrole 
      - run:
          name: Run Ansible Playbook # Ansibleプレイブックを実行
          command: |
            ansible-playbook -i myrole/tests/inventory playbook.yml

  delete-cfn-stack: # スタック削除ジョブ
    executor: python  # Pythonを呼び出し
    steps:
      - checkout  # リポジトリをチェックアウト
      - run:
          name: Delete CloudFormation Stack for RDS #RDSスタックを削除
          command: |
            aws cloudformation delete-stack \
              --stack-name AnsibleStackRDS \
              --region ap-northeast-1
      - run:
          name: Delete CloudFormation Stack for EC2-ALB-SG  #EC2-ALB-SGスタックを削除
          command: |
            aws cloudformation delete-stack \
              --stack-name AnsibleStackEC2-ALB-SG \
              --region ap-northeast-1
      - run:
          name: Delete CloudFormation Stack for VPC #VPCスタックを削除
          command: |
            aws cloudformation delete-stack \
              --stack-name AnsibleStackVPC \
              --region ap-northeast-1

workflows:
  default:
    jobs:
      - setup-environment
      - ansible-playbook:
          requires:
            - setup-environment
      - delete-cfn-stack:
          requires:
            - ansible-playbook

