version: 2.1
orbs:
  python: circleci/python@2.0.3
jobs:
  cfn-lint:
    executor: python/default
    steps:
      - checkout
      - run: pip install cfn-lint
      - run:
          name: run cfn-lint
          command: |
            cfn-lint -i W3002 -t CFn_training20241031/*.yml

  cfn-deploy:
    docker:
      - image: amazon/aws-cli:2.13.7
    steps:
      - checkout
      - run:
          name: Deploy CloudFormation Stack for VPC
          command: |
            aws cloudformation deploy \
              --template-file CFn20240626/VPCtest2406.yml \
              --stack-name TrainingStackVPC\
              --region ap-northeast-1 \
              --capabilities CAPABILITY_NAMED_IAM

workflows:
  raisetech:
    jobs:
      - cfn-lint
      - cfn-deploy