version: 2.1

orbs:
  python: circleci/python@2.0.3  # CircleCIのPython Orbを使用

jobs:
  setup-environment:
    executor:
      name: python/default  # Python OrbのデフォルトExecutorを使用
      tag: "3.8"  # Python 3.8を指定
    steps:
      - checkout  # リポジトリをチェックアウト
      - run:
          name: Install dependencies
          command: |
            sudo yum update
            sudo yum install -y ansible
            pip install --upgrade boto3 botocore
            ansible-galaxy collection install amazon.aws --force

  ansible-playbook:
    executor:
      name: python/default
      tag: "3.8"  # Python 3.8を指定
    steps:
      - checkout  # リポジトリをチェックアウト
      - run:
          name: Run Ansible Playbook to Create CFn
          command: |
            ansible-playbook -i localhost, -c local Ansible_lesson.yml

  delete-cfn-stack:
    executor:
      name: python/default
      tag: "3.8"  # Python 3.8を指定
    steps:
      - checkout  # リポジトリをチェックアウト
      - run:
          name: Run Ansible Playbook to Delete CFn
          command: |
            ansible-playbook -i localhost, -c local delete_cfn.yml

workflows:
  default:
    jobs:
      - setup-environment:
          filters:
            branches:
              only: main  # mainブランチにプッシュされたときのみ実行
      - ansible-playbook:
          requires:
            - setup-environment
      - delete-cfn-stack:
          requires:
            - ansible-playbook

