version: 2.1

orbs:
  python: circleci/python@3.1.0  # 最新バージョンのPython Orbを使用

jobs:
  setup-environment:
    executor:
      name: python/default
      tag: "3.8"  # Python 3.8を指定
    steps:
      - checkout  # リポジトリをチェックアウト
      - run:
          name: Install dependencies
          command: |
            sudo apt update
            sudo apt install -y python3 python3-pip awscli
            pip3 install --upgrade pip
            pip3 install ansible[aws] boto3 botocore
            ansible-galaxy collection install amazon.aws --force
      - run:
          name: Verify Ansible and AnsiblePlaybook Installation
          command: |
            which ansible
            ansible --version
            which ansible-playbook
            ansible-playbook --version
      - run:
          name: Check Installed Files
          command: |
            ls -la ~/.local
            ls -la ~/.local/bin
      - run:
          name: Save dependencies to workspace
          command: |
            mkdir -p ~/workspace
            cp -r ~/.local ~/workspace/
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - .local

      - run:
          name: Create CloudFormation Stack for VPC
          command: |
            aws cloudformation deploy \
              --template-file VPCtest2406.yml \
              --stack-name AnsibleStackVPC \
              --region ap-northeast-1 \
              --capabilities CAPABILITY_NAMED_IAM
      - run:
          name: Create CloudFormation Stack for EC2-ALB-SG
          command: |
            aws cloudformation deploy \
              --template-file EC2,ALB,SG2406.yml \
              --stack-name AnsibleStackEC2-ALB-SG \
              --region ap-northeast-1 \
              --capabilities CAPABILITY_NAMED_IAM
      - run:
          name: Create CloudFormation Stack for RDS
          command: |
            aws cloudformation deploy \
              --template-file RDStest2406.yml \
              --stack-name AnsibleStackRDS \
              --region ap-northeast-1 \
              --capabilities CAPABILITY_NAMED_IAM

  ansible-playbook:
    executor:
      name: python/default
      tag: "3.8"
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Restore dependencies
          command: |
            cp -r ~/workspace/.local ~/
            echo 'export PATH=$PATH:~/.local/bin' >> ~/.bashrc
            source ~/.bashrc
      - checkout
      - run:
          name: Verify Ansible Installation
          command: |
            which ansible
            ansible --version
            which ansible-playbook
            ansible-playbook --version
      - run:
          name: Run Ansible Playbook
          command: |
            ansible-playbook -i myrole/tests/inventory -c local Ansible_lesson.yml

  delete-cfn-stack:
    executor:
      name: python/default
      tag: "3.8"
    steps:
      - checkout  # リポジトリをチェックアウト
      - run:
          name: Delete CloudFormation Stack for RDS
          command: |
            aws cloudformation delete-stack \
              --stack-name AnsibleStackRDS \
              --region ap-northeast-1
      - run:
          name: Delete CloudFormation Stack for EC2-ALB-SG
          command: |
            aws cloudformation delete-stack \
              --stack-name AnsibleStackEC2-ALB-SG \
              --region ap-northeast-1
      - run:
          name: Delete CloudFormation Stack for VPC
          command: |
            aws cloudformation delete-stack \
              --stack-name AnsibleStackVPC \
              --region ap-northeast-1

workflows:
  default:
    jobs:
      - setup-environment:
          filters:
            branches:
              ignore: []  # すべてのブランチで実行
      - ansible-playbook:
          requires:
            - setup-environment
      - delete-cfn-stack:
          requires:
            - ansible-playbook

