version: 2.1
orbs:
  python: circleci/python@2.0.3

jobs:
  setup-environment:
    docker:
      - image: circleci/python:3.9  # Python 3.9を使用
    steps:
      - checkout  # リポジトリをチェックアウト
      - run:
          name: Install dependencies
          command: |
            sudo apt update
            sudo apt install -y ansible
            pip install boto3 botocore amazon.aws

  ansible-playbook:
    docker:
      - image: circleci/python:3.9  # Python 3.9を使用
    steps:
      - checkout  # リポジトリをチェックアウト
      - run:
          name: Run Ansible Playbook to Create CFn
          command: |
            ansible-playbook -i localhost, -c local Ansible_lesson.yml

  delete-cfn-stack:
    docker:
      - image: circleci/python:3.9  # Python 3.9を使用
    steps:
      - checkout  # リポジトリをチェックアウト
      - run:
          name: Run Ansible Playbook to Delete CFn
          command: |
            ansible-playbook -i localhost, -c local delete_cfn.yml

workflows:
  default:
    jobs:
      - setup-environment:
          filters:
            branches:
              only: master  # masterブランチにプッシュされたときのみ実行
      - ansible-playbook:
          requires:
            - setup-environment
      - delete-cfn-stack:
          requires:
            - ansible-playbook
