version: 2.1
orbs:
  python: circleci/python@2.0.3
jobs:
  cfn-lint:
    executor: python/default
    steps:
      - checkout
      - run: pip install cfn-lint
      - run:
          name: run cfn-lint
          command: |
            cfn-lint -i W3002 -t CFn_training20241031/*.yml

  cfn-deploy:
    docker:
      - image: amazon/aws-cli:2.13.7
    steps:
      - checkout
      - run:
          name: Deploy CloudFormation Stack for VPC
          command: |
            aws cloudformation deploy \
              --template-file VPCtest2406.yml \
              --stack-name TrainingStackVPC\
              --region ap-northeast-1 \
              --capabilities CAPABILITY_NAMED_IAM

      - run:
          name: Deploy CloudFormation Stack for EC2_ALB_SG
          command: |
            aws cloudformation deploy \
              --template-file EC2,ALB,SG2406.yml\
              --stack-name TrainingStackEC2_ALB_SG\
              --region ap-northeast-1 \
              --capabilities CAPABILITY_NAMED_IAM

      - run:
          name: Deploy CloudFormation Stack for RDS
          command: |
            aws cloudformation deploy \
              --template-file RDStest2406.yml\
              --stack-name TrainingStackRDS\
              --region ap-northeast-1 \
              --capabilities CAPABILITY_NAMED_IAM

workflows:
  raisetech:
    jobs:
      - cfn-lint
      - cfn-deploy:
          requires:
            - cfn-lint
      - cfn-delete:   #削除したくない場合はここ行をコメントアウト
          requires:   #すべてのジョブが完了した後に実行。削除したくない場合コメントアウト
            - cfn-lint  #削除したくない場合はここ行をコメントアウト
            - cfn-deploy  #削除したくない場合はここ行をコメントアウト

