version: 2.1

orbs:
  python: circleci/python@3.1.0  # 最新バージョンのPython Orbを使用

jobs:
  setup-environment:
    executor:
      name: python/default
      tag: "3.8"  # Python 3.8を指定
    steps:
      - checkout  # リポジトリをチェックアウト
      - run:
          name: Install dependencies
          command: |
            sudo apt update
            sudo apt install -y ansible
            pip install --upgrade boto3 botocore
            ansible-galaxy collection install amazon.aws --force

  ansible-playbook:
    executor:
      name: python/default
      tag: "3.8"
    steps:
      - checkout  # リポジトリをチェックアウト
      - run:
          name: Run Ansible Playbook to Create CFn
          command: |
            ansible-playbook -i localhost, -c local Ansible_lesson.yml

  delete-cfn-stack:
    executor:
      name: python/default
      tag: "3.8"
    steps:
      - checkout  # リポジトリをチェックアウト
      - run:
          name: Run Ansible Playbook to Delete CFn
          command: |
            ansible-playbook -i localhost, -c local delete_cfn.yml

workflows:
  default:
    jobs:
      - setup-environment
      - ansible-playbook:
          requires:
            - setup-environment
      - delete-cfn-stack:
          requires:
            - ansible-playbook

