version: 2.1

orbs:
  python: circleci/python@2.0.3  # CircleCIのPython Orbを使用

jobs:
  setup-environment:
    executor: python/default  # Python OrbのデフォルトExecutorを使用
    steps:
      - checkout  # リポジトリをチェックアウト
      - run:
          name: Install dependencies
          command: |
            sudo apt update
            sudo apt install -y ansible
            pip install boto3 botocore amazon.aws

  ansible-playbook:
    executor: python/default  # Python OrbのデフォルトExecutorを使用
    steps:
      - checkout  # リポジトリをチェックアウト
      - run:
          name: Run Ansible Playbook to Create CFn
          command: |
            ansible-playbook -i localhost, -c local Ansible_lesson.yml

  delete-cfn-stack:
    executor: python/default  # Python OrbのデフォルトExecutorを使用
    steps:
      - checkout  # リポジトリをチェックアウト
      - run:
          name: Run Ansible Playbook to Delete CFn
          command: |
            ansible-playbook -i localhost, -c local delete_cfn.yml

workflows:
  default:
    jobs:
      - setup-environment:
          filters:
            branches:
              only: master  # masterブランチにプッシュされたときのみ実行
      - ansible-playbook:
          requires:
            - setup-environment
      - delete-cfn-stack:
          requires:
            - ansible-playbook

