---
# myrole/nginx/tasks/main.yml

# Nginxをインストール
- name: Install Nginx
  ansible.builtin.shell:
    cmd: |
      sudo apt update && sudo apt install -y nginx

# Nginxを起動して有効化
- name: Start and enable Nginx
  ansible.builtin.shell:
    cmd: |
      sudo systemctl start nginx && sudo systemctl enable nginx
