---
# myrole/nginx/tasks/main.yml

# Nginxをインストール
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present

# Nginxを起動して有効化
- name: Start and enable Nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true