---
# myrole/nginx/tasks/main.yml

# Nginxをインストール
- name: Install Nginx using Amazon Linux Extras
  ansible.builtin.shell:
    cmd: |
      sudo amazon-linux-extras enable nginx1 && sudo amazon-linux-extras install -y nginx
  register: nginx_result
  retries: 5  # 最大5回リトライ
  delay: 60   # 各リトライ間に60秒待機
  until: nginx_result.rc == 0  # コマンドが成功するまで再試行

# Nginxを起動して有効化
- name: Start and enable Nginx
  ansible.builtin.shell:
    cmd: |
      sudo systemctl start nginx && sudo systemctl enable nginx
